// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkdzjjftxwoipvzfnkjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrZHpqamZ0eHdvaXB2emZua2pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4Mzk3ODcsImV4cCI6MjA3NzQxNTc4N30.cHC5wgGZN-7azIHVFbwizUx6Oc-CYT8mp5lGTb6CGoU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});